version: '3.8'
services:

  # MySQL Service
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: mysql
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network
    ports:
      - "3307:3306"

  # PHP Service
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server
    healthcheck:
      test: ["CMD", "php", "artisan", "migrate:status"]
      interval: 5s
      timeout: 20s
      retries: 3
    env_file: ./server/.env
    container_name: trip_report_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      DB_HOST: mysql
    depends_on:
      - mysql
    networks:
      - app-network
    volumes:
      - ./server:/var/www

  # Client Service
  nextjs:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client
    container_name: client
    restart: unless-stopped
    ports:
      - "3006:3000"
    networks:
      - app-network
    volumes:
      - ./client:/app
    command: ["npm", "run", "dev"]

  # Nginx Service
  webserver:
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    image: nginx:alpine
    container_name: trip_report_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "3005:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
